resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:bbyers-pivotal/spring-music.git
    branch: master
    private_key: {{MUSIC_PRIVATE_KEY}}

- name: deploy-development-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_DEV_ORG}}
    space: {{CF_DEV_SPACE}}
    skip_cert_check: true

- name: deploy-test-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_TEST_ORG}}
    space: {{CF_TEST_SPACE}}
    skip_cert_check: true

- name: deploy-uat-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_UAT_ORG}}
    space: {{CF_UAT_SPACE}}
    skip_cert_check: true

- name: deploy-production-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_PROD_ORG}}
    space: {{CF_PROD_SPACE}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: pipeline-artifacts/current-version
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0

- name: music-release
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: deployments/spring-music-(.*).war
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: music-release
    params:
      file: artifact-dir/spring-music-*.war
  - put: music-repo
    params:
      repository: music-repo
      tag: version/number
  - put: version
    params: {file: version/number}
  - put: deploy-development-app
    params:
      manifest: music-repo/manifest-dev.yml
      current_app_name: spring-music
      path: music-release/spring-music-*.war

- name: acceptance-tests
  plan:
  - aggregate:
    - get: music-release
      passed: [build-binary]
      trigger: true
    - get: music-repo
      passed: [build-binary]
      trigger: true
  - put: deploy-test-app
    params:
      manifest: music-repo/manifest-test.yml
      current_app_name: spring-music
      path: music-release/spring-music-*.war
  - task: verify
    file: music-repo/ci/tasks/verify-test.yml
    params:
      MUSIC_URL: http://spring-music-test.local.pcfdev.io

- name: promote-to-uat
  plan:
  - aggregate:
    - get: music-release
      passed: [acceptance-tests]
      trigger: true
    - get: music-repo
      passed: [acceptance-tests]
      trigger: true
  - put: deploy-uat-app
    params:
      manifest: music-repo/manifest-uat.yml
      current_app_name: spring-music
      path: music-release/spring-music-*.war

- name: manual-deploy-to-prod
  serial: true
  plan:
  - aggregate:
    - get: music-release
      passed: [promote-to-uat]
    - get: music-repo
      passed: [promote-to-uat]
  - put: deploy-production-app
    params:
      manifest: music-repo/manifest-prod.yml
      current_app_name: spring-music
      path: music-release/spring-music-*.war
